version: "3.8"

services:
  
  postgres:
    image: postgres:latest
    container_name: postgres-strapi
    environment:
      POSTGRES_USER: strapi 
      POSTGRES_PASSWORD: strapi 
      POSTGRES_DB: strapi 
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - strapi-router

  cms-server:
    container_name: cms-server
    image: thanhtien2094/cms-server:v1.0
    environment:
      - DATABASE_HOST=postgres-strapi
    ports:
      - "1337:1337"
    networks:
      - strapi-router
    depends_on:
      - postgres
  
volumes:
  pg_data:

networks:
  strapi-router:
